name: Python application

on: [push]

jobs:
  build:

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Create dot env file
        run: |
          touch .env
          echo 'DB_CONTAINER_NAME=${{ secrets.DB_CONTAINER_NAME }}' >> .env
          echo 'PYTHON_CONTAINER_NAME=${{ secrets.PYTHON_CONTAINER_NAME }}' >> .env
          echo 'DB_NAME=${{ secrets.DB_NAME }}' >> .env
          echo 'DB_PASSWORD=${{ secrets.DB_PASSWORD }}' >> .env
          echo 'DB_USER=${{ secrets.DB_USER }}' >> .env
          echo 'DB_IMAGE_NAME=${{ secrets.DB_IMAGE_NAME }}' >> .env
          echo 'PYTHON_IAMGE_NAME=${{ secrets.PYTHON_IMAGE_NAME }}' >> .env
          echo 'PYTHON_PORT=${{ secrets.PYTHON_PORT }}' >> .env
          echo 'DB_PORT=${{ secrets.DB_PORT }}' >> .env
          echo 'DB_IP=${{ secrets.DB_IP }}' >> .env
          echo 'PYTHON_IP=${{ secrets.PYTHON_IP }}' >> .env
          echo 'DB_SERVICE_NAME=${{ secrets.DB_SERVICE_NAME }}' >> .env
          echo 'PYTHON_SERVICE_NAME=${{ secrets.PYTHON_SERVICE_NAME }}' >> .env
      - name: Build
        shell: bash
        run: |
          sh docker/build.sh
          docker-compose exec -T python3 sh -c 'chmod -R +x .  && ./build.sh && ./test/test_mysql.sh'
