name: Python application

on:
  push:
    branches:
    - 'feature/**'

jobs:
  build:

    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'feature')
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sh build-docker.sh
          sh exec.sh
      - name: test
        run: sh build.sh
