name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sh build-docker.sh
          sh exec.sh
      - name: Test
        run: sh build.sh
